---
title: "Mapping The Impact of Internal Migration Across Europe"
draft: false
author: "Francisco Rowe"
date: '2020-02-08'
categories: ["R"]
tags: ["Spatial Analysis", "Migration", "Spatial Impact", "Europe"]
---


# Net Internal Migration Rate Across Europe

At the end of last year, we published a paper assessing the impact of internal migration on redistributing population within European countries. Specifically we assessed the impact of internal migration on promoting population concentration or deconcentration. Below is a thread I posted on Twitter summarising key aspects of the paper. The paper is [open access](http://dx.doi.org/10.12765/CPoS-2019-18en) - see reference at the end of this post.

**Why this matters?** First, while considerable attention is devoted to international migration, the number of internal migration (763 million) is significantly greater -almost 3 times that of international migrants (272 million)

Second, the spatial impact of internal migration on population redistribution is arguably the most visible and significant aspect of human population movement, increasing population numbers in a few locations while reducing numbers elsewhere, transferring skills and knowledge, affecting labour and housing markets

Third, **The GAP** contemporary understanding of the way migration impacts on settlement patterns remains crude, constrained primarily by reliance on coarse urban-rural dichotomies, data inadequacies and the perennial obstacles by the MAUP

**RESULTS** show (1) that the overall redistributive impact of internal migration is low in most European countries but the mechanisms differ across the continent

(2) About half the European countries are experiencing a process of concentration toward urbanised regions, particularly in Northern, Central and Eastern Europe i.e. population redistribution is directed toward more densely populated regions, leading to population concentration or re-urbanisation

(3) We showed these patterns of population concentration are driven by different but distinctive process: (i) population gains in major urban centres, (ii) localised urban sprawl, and (iii) concentration of population gains in small dense areas

(4) By contrast, countries in the West and South are undergoing a process of population deconcentration resulting from population gains are focused on lower-density regions

(5) A number of countries (Norway, Lithuania, Estonia, Spain, the UK & Italy) have reached a spatial equilibrium: internal migration minimally alters the existing pattern of population settlement

*These findings* demonstrate the important variations in the patterns of population redistribution in Europe highlighting the diminishing impact of migration in shaping settlement patterns in highly urbanised countries and also lend support to the idea of diverse trajectories in population redistribution for countries at the upper end of development ladder

The map below reveals the patterns of population gains and losses through internal migration. For this map, net migration rates based on administrative areas are superimposed on a base layer showing the major nodes of human settlement, which helps identify the urban areas gaining or losing population from internal migration. Based on country-specific means and standard deviations, standardised net migration rates (z-scores) are reported to help pinpoint areas of unusually high net migration gains or losses; that is, z-scores two standard deviations outside the mean. 

The results reveal that diverse migration processes underpin the overall processes of population concentration. In Belarus, Portugal, Denmark and Russia, population concentration was driven by unusually high migration gains in a handful of large urban centres, while migration losses were found in sparsely populated areas. Significant gains occurred in the cities of Pinsk, Grodno and Polotsk in Belarus; in the Península de Setúbal within the Lisbon region in Portugal; in the Copenhagen metropolitan area in Denmark; and in Moscow and St Petersburg in Russia.

By contrast, patterns of population concentration in Switzerland, Bulgaria, Germany, Finland, the Netherlands, Turkey, Austria, Hungary and Sweden are the result of different processes. In Turkey and Switzerland, significant migration gains in dense small urban areas and heavy losses in a small number of remote rural locations shaped overall patterns of population concentration. In Austria, Bulgaria, Hungary and Sweden, population concentration occurred in large cities, and their satellites, most notably in the areas of Vienna, Sofia, Budapest and Gothenburg. In Germany, on the other hand, migration gains were concentrated in middle-sized and small cities with widespread losses in more remote areas. For example, significant gains occurred in Dresden, Leipzig, Potsdam (near Berlin) and Tübingen (near Stuttgart), while acute losses were observed in Göttingen and around Cottbus in the east of Germany. Patterns of urban sprawl in Germany are largely a response to high property prices in large urban agglomerations.

**References**

Rowe, F., Bell, M., Bernard, A., Charles-Edwards, E. and Ueffing, P., 2019. Impact of Internal Migration on Population Redistribution in Europe: Urbanisation, Counterurbanisation or Spatial Equilibrium?. *Comparative Population Studies*, 44: 201-34. doi: http://dx.doi.org/10.12765/CPoS-2019-18en
